runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /_ah/(mapreduce|queue|warmup).*
  script: wsgi.application
  secure: always
  login: admin

- url: /(admin).*
  script: wsgi.application
  secure: always
  login: admin

- url: /.*
  script: wsgi.application
  secure: always

skip_files:
# default values first
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# no tests need to be included
- ^(.*/)?tests.py$
- ^(.*/)?tests/*$
